"""empty message

Revision ID: 9d885a8b4fbc
Revises: 79704c4fa783
Create Date: 2025-03-19 08:38:52.597296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d885a8b4fbc'
down_revision = '79704c4fa783'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   
    op.add_column('todos',sa.Column('completed', sa.Boolean(), nullable=True))
    op.execute('UPDATE todos SET completed = false WHERE completed IS NULL')
    op.alter_column('todos', 'completed', existing_type=sa.BOOLEAN(), nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.drop_column('completed')

    # ### end Alembic commands ###
